main: net.dusterthefirst.lockedServers.Main
version: 0
name: SecureServers
author: DusterTheFirst
description: Server Locking Tool

commands:
    SS:
        description: "The Administration Command For SecureServers"
        usage: "/SS password <password>"